[backport] add CFI and size info to external assembly
rust-embedded/cortex-m-rt pull request #295
Opened 2020-09-04 13:25 UTC by japaric

backport of #294

2020-09-04 13:25 UTC, rust-highfive commented
r? @thalesfragoso

(rust_highfive has picked a reviewer for you, use r? to override)

2020-09-04 13:25 UTC, rust-highfive commented
:warning: **Warning** :warning:

* Pull requests are usually filed against the master branch for this repo, but this one is against v0.6.x. Please double check that you specified the right target!

2020-09-04 13:27 UTC, therealprof requested changes
LGTM but we should have a CHANGELOG entry since we're probably going to publish this, right?

2020-09-07 17:18 UTC, jonas-schievink approved these changes
bors r+

2020-09-07 17:23 UTC, therealprof approved these changes
LGTM. Thanks!

bors r+

2020-09-07 17:35 UTC, merged